language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "dzil authordeps | xargs cpanm"
  - "cpanm -n Devel::Cover::Report::Coveralls"
install: "dzil listdeps | xargs cpanm"
script: 
  - "dzil test"
  - "perl Build.PL && ./Build build && cover -test -report coveralls"
