name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cpanminus
      run: apt-get install cpanminus
    - name: Install Dist::Zilla stuff
      run: cpanm Dist::Zillacpanm Devel::Cover::Report::Coveralls Dist::Zilla::App::Command::cover
