name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to Github Docker Package Registry
      run: echo ${GITHUB_PACKAGE_REGISTRY_PASSWORD} | docker login -u ${GITHUB_PACKAGE_REGISTRY_LOGIN} --password-stdin docker.pkg.github.com
      with:
        GITHUB_PACKAGE_REGISTRY_LOGIN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_LOGIN }}
        GITHUB_PACKAGE_REGISTRY_PASSWORD: ${{ secrets.GITHUB_PACKAGE_REGISTRY_PASSWORD }}
      
    - name: Build project using 'Perl-CI/github-action-perl-dzil-build@master'
      uses: Perl-CI/github-action-perl-dzil-build@master
