name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Publish Docker Image to Github Package Registry
      uses: Perl-CI/github-action-perl-dzil-build@master
