name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to Github Docker Package Registry
      run: docker login docker.pkg.github.com --username ${GITHUB_PACKAGE_REGISTRY_LOGIN} --password "${GITHUB_PACKAGE_REGISTRY_PASSWORD}"
      env:
        GITHUB_PACKAGE_REGISTRY_LOGIN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_LOGIN }}
        GITHUB_PACKAGE_REGISTRY_PASSWORD: ${{ secrets.GITHUB_PACKAGE_REGISTRY_PASSWORD }}
      
    #- name: Build project using 'Perl-CI/github-action-perl-dzil-build@master'
    #  uses: Perl-CI/github-action-perl-dzil-build@master
